sudo: false

language: java
jdk:
- oraclejdk8

# Override default Travis install step that calls `./gradlew assemble`.
install: true

script: ci/build.sh

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
